### ISSUE TITLE
Program needs some updates

### ISSUE THREAD

**Issue by KL3N1** [eastpriSs/TranslatorUniversityAssembly#1]
Issues никто не читает, поэтому кто это прочитал вот тебе рецепт маринада с айраном под шашлыки из свинины:
Ингредиенты:
Свинина (окорок) - 2-2,5 кг
Маринад с аджикой:
Аджика - 2-3 ч. л.
Майонез - 2-3 ст. л.
Лук репчатый - 1-2 шт.
Соль - по вкусу
Перец черный молотый - по вкусу

Маринад из айрана:
Айран – 0,5 л
Лук репчатый - 1 шт.
Соль - по вкусу
Перец черный молотый - по вкусу

Подготавливаем продукты для шашлыка из свинины.
Мясо отделяем от пленок и режем средними кусочками. Делим мясо на две равные части.
Лук нарезаем полукольцами.
В одну тарелку с мясом добавляем лук, немного майонеза и пару ложек аджики. Немного солим, перчим и перемешиваем.
В другую тарелку с мясом также добавляем лук, перец, соль и заливаем мясо айраном. Перемешиваем и отставляем в сторонку.
Получившееся мясо перекладываем по пакетам и оставляем мариноваться на 2-3 часа.
По истечении данного отрезка времени готовим шашлык из свинины на мангале. Очень важно его не передержать, чтобы мясо получилось сочным!
Шашлык из свинины готов. Приятного аппетита!

**Comment by eastpriSs** [comment]
Спасибо большое. Мой мангал расхуярили мама не балуй. Но свинину я не ем(
